POST http://localhost:5015/SV8/Certificates/Insert/ColumnExist
Content-Type: application/json

{
  "username": "",
  "password": "",
  "name": "",
  "date": "",
  "plantNo": "",
  "lat": "",
  "lng": ""
}
